### ISSUE TITLE
add gh-f

### ISSUE THREAD

**Issue by gennaro-tedesco** [kodepandai/awesome-gh-cli-extensions#1]
I have written a `gh` extension that I would like to add to the list (but I have found no contributing guidelines in the README): [gh-f](https://github.com/gennaro-tedesco/gh-f), a compact and snappy wrapper around `gh` basic functionalities that makes use of `fzf` and its properties.

Link to the repository: https://github.com/gennaro-tedesco/gh-f

Feel free to ignore if you deem it irrelevant :)

**Comment by axmad386** [comment]
@lakuapik can you help?

**Comment by lakuapik** [comment]
@gennaro-tedesco Thank you. Added here https://github.com/kodepandai/awesome-gh-cli-extensions/commit/37794bd04eaa8683d9b8622558bd0363fa081fb9.
