### ISSUE TITLE
Remove `gh-extension` topic from this repository

### ISSUE THREAD

**Issue by mislav** [kodepandai/awesome-gh-cli-extensions#19]
Hi, thanks for maintaining a list of awesome CLI extensions. 

GitHub CLI searches repositories with the `gh-extension` topic to programmatically discover installable extensions. Your repository has that topic, but it isn't an extension one can install. It would be helpful if you removed the misleading topic, since that would make `gh extension search` command more efficient. Thank you!

**Comment by lakuapik** [comment]
@mislav removed, thanks.
